# This is a basic workflow to help you get started with Actions

name: CI/CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    needs: build  
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev, staging, prod]
    environment: ${{ matrix.environment }}
    steps:
      - uses: actions/checkout@v3

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.3.0

      - name: Check Cluster
        run: |
          kubectl config get-contexts
          kubectl get ns

      - name: Install Chart
        run: |
          helm upgrade  --create-namespace --install helm-template-${{ matrix.environment }} stable/.

      - name: Wait to deploy
        run: sleep 10s
        shell: bash

      - name: Check Installation
        run: |
          helm ls -A
          kubectl get all